// Code generated by ogen, DO NOT EDIT.

package manage

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// GetRaftNodeParams is parameters of getRaftNode operation.
type GetRaftNodeParams struct {
	// Get leader node.
	IsLeader OptBool
}

func unpackGetRaftNodeParams(packed middleware.Parameters) (params GetRaftNodeParams) {
	{
		key := middleware.ParameterKey{
			Name: "isLeader",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.IsLeader = v.(OptBool)
		}
	}
	return params
}

func decodeGetRaftNodeParams(args [0]string, argsEscaped bool, r *http.Request) (params GetRaftNodeParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: isLeader.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "isLeader",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIsLeaderVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotIsLeaderVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IsLeader.SetTo(paramsDotIsLeaderVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "isLeader",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
