name: build

on:
  workflow_call:
    inputs:
      hub:
        required: true
        default: "ghcr.io"
        type: string
      tags:
        required: true
        default: "latest"
        type: string
        description: "tags for docker images"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker metadata setup
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{inputs.hub}}/${{github.repository}}
          tags: ${{ inputs.tags }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: '.'
          file: './cmd/cokane-authz/Dockerfile'
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
