name: develope-uninstall

on:
  delete:
    branches:
      - feature/*

jobs:
  versioning:
    permissions: write-all
    runs-on: kubernetes
    outputs:
      tags: ${{ steps.result.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"
      - name: Extract Workspace Name
        id: extract-workspace-name
        run: |
          TEMP_BRANCH_NAME=$(echo ${{ github.event.ref }} | sed -E 's|refs/heads/(.+)|\1|')
          TEMP_WORKSPACE_NAME=$(echo $TEMP_BRANCH_NAME | tr '/' '-')

          echo "branch_name=$TEMP_BRANCH_NAME"            >> $GITHUB_OUTPUT
          echo "workspace_name=$TEMP_WORKSPACE_NAME"      >> $GITHUB_OUTPUT
      - name: Destroy Resources
        run: |
          echo "::notice ::Deleting ${{ steps.extract-workspace-name.outputs.workspace_name }}"

          cd ./scripts/deploy-devapp

          terraform init
          terraform workspace select '${{ steps.extract-workspace-name.outputs.workspace_name }}'
          terraform destroy -auto-approve -set="branch=${{ steps.extract-workspace-name.outputs.branch_name }}"
          terraform workspace delete '${{ steps.extract-workspace-name.outputs.workspace_name }}''
