name: kubetest

on:
  workflow_dispatch:
jobs:
  versioning:
    permissions: write-all
    runs-on: kubernetes
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get -n cokane-authz pods
      - name: Log
        run: |
          echo "::notice ::Current  : ${{ steps.semver.outputs.current }}"
          echo "::notice ::Next     : ${{ steps.semver.outputs.value }}"
